name: Deploy to S3
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install Dependencies
        run: npm ci
        env:
          HUSKY: 0
      - name: Build Application
        run: npm run build
      - name: Configure
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-region: "${{ secrets.AWS_REGION }}"
          role-to-assume: "${{ secrets.AWS_ROLE }}"
          role-session-name: "GitHub-Actions_Publish_Static_Site"
      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist/ s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete --region ${{ secrets.AWS_REGION }}
      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --distribution-id ${{secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"